#配置端口号
server:
  port: 8080
  servlet:
    context-path: /
    session:
      timeout: 600s


# 配置mybatis
mybatis:
  # 注册映射文件
  mapper-locations: classpath:com/guo/dao/*.xml
  # 注册实体类所在的包，为实体类注册别名(便于xml配置)
  type-aliases-package: com.guo.pojo

# 注册数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: gj001212

  redis:
    host: redisOS7
    port: 6379

  cache:
    # 指定缓存类型
    type: redis
    # 指定当前应用所使用的缓存空间的名称
    cache-names: guojun

logging:
  level:
    com.guo.dao: debug